routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('home');
});


Route::get('/home', function () {
    return view('home');
});

Route::group(['middleware' => ['check.roles:CREATE'], 'prefix' => 'manage'],function () {
    Route::get('/', 'ManageController@index')->name('manage.index');
    Route::get('/content/categories', 'ManageController@categories')->name('manage.content_categories');
    Route::get('/content/articles', 'ManageController@articles')->name('manage.content_articles');
    Route::get('/content/tags', 'ManageController@tags')->name('manage.content_tags');
    Route::get('/users', 'ManageController@users')->name('manage.users');
    Route::get('/reports', 'ManageController@reports')->name('manage.reports');
    Route::get('/forum', 'ManageController@forum')->name('manage.forum');
});


Route::resource('categories', 'CategoryController');
Route::resource('articles', 'ArticleController');
Route::resource('tags', 'TagController');

Auth::routes();

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Tag extends Model
{
    protected $fillable = [
        'title',
    ];
    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value,'-');
        $this->attributes['user_id'] = Auth::id();
    }
    public function articles(){
        return $this->belongsToMany(Article::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Action;
use App\Events\NewAction;
use App\Tag;
use App\Http\Requests\TagAddOrEditRequest;
use Illuminate\Http\Request;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('check.roles:CREATE,UPDATE,DELETE')->except(['index','show']);
        $this->middleware('check.roles:CREATE')->only(['create','store']);
        $this->middleware('check.roles:UPDATE')->only(['edit','update']);
        $this->middleware('check.roles:DELETE')->only(['destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::With('articles')->get();
        return view('tags.index', compact("tags"));
    }


    public function create()
    {
        return view('tags.create');
    }

    public function store(TagAddOrEditRequest $request)
    {
        $elmt = new Tag($request->all());
        $elmt->save();
        event(new NewAction(new Action(['target' => strtoupper(substr(get_class(),21,-10)), 'action' => strtoupper(__FUNCTION__), 'user_id' => $request->user()->id,'elmt_id' => $elmt->id])));
        return redirect()->route('tags.index');
    }

    public function show(Tag $tag)
    {
        return view('tags.show', ['tag' => $tag]);
    }

    public function edit(Tag $tag)
    {
        return view('tags.edit', ['tag' => $tag]);
    }

    public function update(TagAddOrEditRequest $request, Tag $elmt)
    {
        $elmt->update($request->all());
        event(new NewAction(new Action(['target' => strtoupper(substr(get_class(),21,-10)), 'action' => strtoupper(__FUNCTION__), 'user_id' => $request->user()->id,'elmt_id' => $elmt->id])));
        return redirect()->route('tags.show', ['tag' => $elmt]);
    }

    public function destroy(Request $request, int $elmt)
    {
        event(new NewAction(new Action(['target' => strtoupper(substr(get_class(),21,-10)), 'action' => strtoupper(__FUNCTION__), 'user_id' => $request->user()->id,'elmt_id' => $elmt])));
        Tag::destroy($elmt);
        return redirect()->route('tags.index');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.website')

@section('contentPage')
        <div class="col-12">
            <h1>Création</h1>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {!! Form::open(array('route' => array('tags.store'),'method' => 'post') )!!}
            <div class="form-group">
                    {!! Form::label('title', 'Titre') !!}
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}


                    {!! Form::submit('Créer', ['class' => 'btn btn-primary']) !!}
            </div>
            {!! Form::close() !!}
        </div>
@stop

resources/views/tags/edit.blade.php
@extends('layouts.website')


@section('contentPage')
    <div class="col-12">
        <h1>Modification</h1>
        <div class="form-group">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {!! Form::model($tag,["route" => array('tags.update',$tag),"method" => "put"]) !!}

            {!! Form::label('title', 'Titre') !!}
            {!! Form::text('title', null, ['class' => 'form-control']) !!}


            {!! Form::submit('Modifier', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/tags/index.blade.php
@extends('layouts.website')


@section('contentPage')
    <div class="col-12">
        <h1>Tags</h1>
        <div class="categoroes col-12 row">
            @foreach ($tags as $tag)
                <article style="height:200px;margin-top:60px;" class="col-lg-4">
                <a style="color: black;"href="{{route('tags.show',['category' => $tag->id])}}"><h2 style="border-bottom:1px solid #749291;font-size:1.2em; text-align:center;padding-bottom: 10px;">{{$tag->title}}</h2></a>

                @auth
                    @if (Auth::user()->hasRight('UPDATE'))
                        {!! Form::open(array('route' => array('tags.edit', $tag->id),'method' => 'get','style'=>'display:inline-block')) !!}
                        {!! Form::submit('Modifier', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    @endif
                    @if (Auth::user()->hasRight('UPDATE'))
                        {!! Form::open(array('route' => array('tags.destroy', $tag->id),'method' => 'delete', 'style'=>'display:inline-block')) !!}
                        {!! Form::submit('Supprimer', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    @endif
                @endauth
                </article>
            @endforeach
        </div>
    </div>
@stop

resources/views/tags/show.blade.php
@extends('layouts.website')


@section('contentPage')
    <div class="col-12">
        <div class="categories">
            <h1>{{$tag->title}}</h1>
            <h2>Slug : {{$tag->slug}}</h2>
        </div>
        {!! Form::model($tag,["route" => array('tags.destroy',$tag), "method" => "delete"]) !!}
        {!! Form::submit("Supprimer",['class' => 'btn btn-primary','style' => 'display:inline-block']) !!}
        {!! Form::close() !!}

        {!! Form::model($tag,["route" => array('tags.edit',$tag), "method" => "get"]) !!}
        {!! Form::submit("Modifier",['class' => 'btn btn-primary', 'style' => 'display:inline-block']) !!}
        {!! Form::close() !!}
        <div class="tags col-12 row">
        @foreach ($tag->articles as $article)
            <article style="height:200px;margin-top:60px;" class="col-lg-4">
            <a style="color: black;"href="{{route('articles.show',['article' => $article->id])}}"><h2 style="border-bottom:1px solid #749291;font-size:1.2em; text-align:center;padding-bottom: 10px;">{{$article->title}}</h2></a>
            <p style="min-height:70px;"l>{{substr($article->content,0,100)}}</p>

            <ul>
                <li>Catégorie :  <a href="{{ route('categories.show',['category' => $article->category->id]) }}"> {{ $article->category->title }} </a></li>
                <li>Article créé le : {{$article->created_at->format('D d M Y')}}</li>
                <li>Article modifié le : {{$article->updated_at->format('D d M Y')}}</li>
            </ul>
            {!! Form::open(array('route' => array('articles.update', $article->id),'method' => 'get','style'=>'display:inline-block')) !!}
            {!! Form::submit('Modifier', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
            {!! Form::open(array('route' => array('articles.destroy', $article->id),'method' => 'delete', 'style'=>'display:inline-block')) !!}
            {!! Form::submit('Supprimer', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
            </article>
        @endforeach
        </div>
    </div>
@stop