routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('home');
});


Route::get('/home', function () {
    return view('home');
});

Route::group(['middleware' => ['check.roles:CREATE'], 'prefix' => 'manage'],function () {
    Route::get('/', 'ManageController@index')->name('manage.index');
    Route::get('/content/categories', 'ManageController@categories')->name('manage.content_categories');
    Route::get('/content/articles', 'ManageController@articles')->name('manage.content_articles');
    Route::get('/content/tags', 'ManageController@tags')->name('manage.content_tags');
    Route::get('/users', 'ManageController@users')->name('manage.users');
    Route::get('/reports', 'ManageController@reports')->name('manage.reports');
    Route::get('/forum', 'ManageController@forum')->name('manage.forum');
});


Route::resource('categories', 'CategoryController');
Route::resource('articles', 'ArticleController');
Route::resource('tags', 'TagController');

Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/manage.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/adminui/assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!-- This page css -->
    <!-- Custom CSS -->
    <link href="/adminui/dist/css/style.min.css" rel="stylesheet">
<link href="/adminui/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->
</head>

<body>
<!-- ============================================================== -->
<!-- Preloader - style you can find in spinners.css -->
<!-- ============================================================== -->
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================== -->
<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
@include('layouts.manage_head')
<!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="sidebar-item {{ (request()->is('manage')) ? 'selected' : '' }}">
                        <a class="sidebar-link sidebar-link" href="{{route('manage.index')}}"
                                                 aria-expanded="false"><i data-feather="home" class="feather-icon"></i><span
                                class="hide-menu">Accueil</span></a></li>
                    <li class="list-divider"></li>
                    <li class="sidebar-item {{ (request()->segment(2) == 'content') ? 'selected' : '' }}">
                        <a class="sidebar-link has-arrow {{ (request()->is('manage/content*')) ? 'selected active' : '' }}" href="javascript:void(0)"
                                                 aria-expanded="false"><i data-feather="grid" class="feather-icon"></i><span
                                class="hide-menu">Contenu </span></a>
                        <ul aria-expanded="false" class="collapse  first-level base-level-line {{(request()->segment(2) == 'content') ? 'in' : '' }}">
                            <li class="sidebar-item {{ (request()->is('manage/content/categories')) ? 'active' : '' }}"><a href="{{route('manage.content_categories')}}" class="sidebar-link {{ (request()->is('manage/content/categories')) ? 'active' : '' }}"><span
                                        class="hide-menu"> Catégories
                                        </span></a>
                            </li>
                            <li class="sidebar-item  {{ (request()->is('manage/content/articles')) ? 'active' : '' }}"><a href="{{route('manage.content_articles')}}" class="sidebar-link {{ (request()->is('manage/content/articles')) ? 'active' : '' }}"><span
                                        class="hide-menu"> Articles
                                        </span></a>
                            </li>
                            <li class="sidebar-item  {{ (request()->is('manage/content/tags')) ? 'active' : '' }}"><a href="{{route('manage.content_tags')}}" class=" {{ (request()->is('manage/content/tags')) ? 'active' : '' }} sidebar-link"><span
                                        class="hide-menu"> Tags
                                        </span></a>
                            </li>

                        </ul>
                    </li>
                    <li class="sidebar-item {{ (request()->is('manage/reports')) ? 'active' : '' }}"> <a class="sidebar-link" href="{{route('manage.reports')}}"
                                                 aria-expanded="false"><i data-feather="tag" class="feather-icon"></i><span
                                class="hide-menu">Signalements
                                </span></a>
                    </li>
                    <li class="sidebar-item {{ (request()->is('manage/forum')) ? 'active' : '' }}"> <a class="sidebar-link" href="{{route('manage.forum')}}"
                                                                                                         aria-expanded="false"><i data-feather="message-square" class="feather-icon"></i><span
                                class="hide-menu">Forum
                                </span></a>
                    </li>

                    <li class="list-divider"></li>

                    <li class="sidebar-item"> <a class="sidebar-link sidebar-link" href="#"
                                                 aria-expanded="false"><i data-feather="log-out" class="feather-icon"></i><span
                                class="hide-menu">Se déconnecter</span></a></li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">{{$title}}</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="/adminui/html/index.html" class="text-muted">Management</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">{{ $title }}</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">

            @yield('contentPage')
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

                <footer class="footer text-center text-muted">
            All Rights Reserved by Adminmart. Designed and Developed by <a
                href="https://wrappixel.com">WrapPixel</a>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->

<script src="/adminui/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="/adminui/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/adminui/dist/js/pages/datatable/datatable-basic.init.js"></script>
<script src="/adminui/assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="/adminui/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- apps -->
<script src="/adminui/dist/js/app-style-switcher.js"></script>
<script src="/adminui/dist/js/feather.min.js"></script>
<script src="/adminui/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
<script src="/adminui/dist/js/sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="/adminui/dist/js/custom.min.js"></script>
</body>

</html>

resources/views/layouts/manage_head.blade.php
<header class="topbar" data-navbarbg="skin6">
        <nav class="navbar top-navbar navbar-expand-md">
            <div class="navbar-header" data-logobg="skin6">
                <!-- This is for the sidebar toggle which is visible on mobile only -->
                <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                        class="ti-menu ti-close"></i></a>
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-brand">
                    <!-- Logo icon -->
                    <a href="/adminui/html/index.html">
                        <b class="logo-icon">
                            <!-- Dark Logo icon -->
                            <img src="/adminui/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                            <!-- Light Logo icon -->
                            <img src="/adminui/assets/images/logo-icon.png" alt="homepage" class="light-logo" />
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span class="logo-text">
                                <!-- dark Logo text -->
                                <img src="/adminui/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                            <!-- Light Logo text -->
                                <img src="/adminui/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                            </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Toggle which is visible on mobile only -->
                <!-- ============================================================== -->
                <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
                   data-toggle="collapse" data-target="#navbarSupportedContent"
                   aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i
                        class="ti-more"></i></a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="navbar-nav float-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <img src="/adminui/assets/images/users/profile-pic.jpg" alt="user" class="rounded-circle"
                                 width="40">
                            <span class="ml-2 d-none d-lg-inline-block"><span>Hello,</span> <span
                                    class="text-dark">{{Auth::user()->name}}</span> <i data-feather="chevron-down"
                                                                                       class="svg-icon"></i></span>
</a>
<div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
    <a class="dropdown-item" href="javascript:void(0)"><i data-feather="user"
                                                          class="svg-icon mr-2 ml-1"></i>
        Profil</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="javascript:void(0)"><i data-feather="power"
                                                          class="svg-icon mr-2 ml-1"></i>
        Se déconnecter</a>

</div>
</li>
<!-- ============================================================== -->
<!-- User profile and search -->
<!-- ============================================================== -->
</ul>
<ul class="navbar-nav float-left">

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle pl-md-3 position-relative" href="javascript:void(0)"
           id="bell" role="button" data-toggle="dropdown" aria-haspopup="true"
           aria-expanded="false">
            <span><i data-feather="bell" class="svg-icon"></i></span>
            <span class="badge badge-primary notify-no rounded-circle">5</span>
        </a>
        <div class="dropdown-menu dropdown-menu-left mailbox animated bounceInDown">
            <ul class="list-style-none">
                <li>
                    <div class="message-center notifications position-relative">
                        <!-- Message -->
                        <a href="javascript:void(0)"
                           class="message-item d-flex align-items-center border-bottom px-3 py-2">
                            <div class="btn btn-danger rounded-circle btn-circle"><i
                                    data-feather="airplay" class="text-white"></i></div>
                            <div class="w-75 d-inline-block v-middle pl-2">
                                <h6 class="message-title mb-0 mt-1">Luanch Admin</h6>
                                <span class="font-12 text-nowrap d-block text-muted">Just see
                                                        the my new
                                                        admin!</span>
                                <span class="font-12 text-nowrap d-block text-muted">9:30 AM</span>
                            </div>
                        </a>

                    </div>
                </li>
                <li>
                    <a class="nav-link pt-3 text-center text-dark" href="javascript:void(0);">
                        <strong>Voir tout</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </div>
    </li>
</ul>

</div>
</nav>
</header>

resources/views/layouts/website.blade.php
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Sound of News</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Sound Of News') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{route('articles.index') }}">{{ __('Articles') }}</a>
                </li>
                @auth
                    @if (Auth::user()->hasRight('UPDATE') or Auth::user()->hasRight('DELETE'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('categories.index') }}">{{ __('Catégories') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('tags.index') }}">{{ __('Tags') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('manage.index') }}">{{ __('Administration') }}</a>
                        </li>
                    @endif
                @endauth
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('S\'identifier') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Inscription') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Se déconnecter') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-5">
    @yield('contentPage')
</div>
</body>
<script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
<script type="module" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/esm/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>